### ISSUE TITLE
PHPstudy中发现的一个问题

### ISSUE THREAD

**Issue by shutaG** [xiaodit/think-admin#11]
在默认的情况下，登录后请求 info 接口时，会报获取token失败的情况。经排查发现为环境原因。
解决方案：
在public  htaccess文件中增加一行
RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]   这行下边增加以下内容
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0

**Comment by edenleung** [comment]
感谢 已修复
