### ISSUE TITLE
预览地址和文档都打不开了

### ISSUE THREAD

**Issue by DanRan-hcy** [xiaodit/think-admin#23]

**Comment by edenleung** [comment]
尝试以下地址

- 预览
https://ant-design-vue-edenleung.cloud.okteto.net
- 文档
https://tant-doc-edenleung.cloud.okteto.net

**Comment by edenleung** [comment]
预览地址登录不了（估计被人删除数据了），你可以先下载到本地测试。

**Comment by DanRan-hcy** [comment]
> 预览地址登录不了（估计被人删除数据了），你可以先下载到本地测试。

多谢，已加群，希望多学习学习

**Comment by edenleung** [comment]
加油。
