### ISSUE TITLE
功能需求清单

### ISSUE THREAD

**Issue by edenleung** [xiaodit/think-admin#5]
请告诉我有哪个基础功能要开发的

**Comment by tlerbao** [comment]
权限管理：基于角色的权限管理越强大越好；支持无限级父子级权限继承，父级的管理员可任意增删改子级管理员及权限设置（子级管理员管理其下级角色时只可以授权本身有的权限）。

数据授权：业务系统应用广泛，极其重要，ThinkPHP的后台系统没有三十也有二十，基本只有权限管理没有数据授权，Fastadmin有一个简易的但不够强大。

数据授权可参考码云搞的开源项目评选冠军产品：若依后台管理系统 http://www.ruoyi.vip/；

数据授权起码应做到，可以定义只能看自己、看部门、看部门及以下、看所有、自定义等。

盼望越来越好。

**Comment by edenleung** [comment]
不错，有些地方可以借鉴

**Comment by az18780007577** [comment]
代码拉下来数据库表里没有初始的管理员数据....能加一条admin的进去吗?

**Comment by edenleung** [comment]
> 代码拉下来数据库表里没有初始的管理员数据....能加一条admin的进去吗?

修复了，重新执行`php think migrate:run`

https://github.com/edenleung/think-admin/blob/6.0/database/migrations/20191218051507_create_data.php#L84
