### ISSUE TITLE
🐛[Bug]个人设置页面切换屏幕时，菜单显示异常。

### ISSUE THREAD

**Issue by edenleung** [xiaodit/think-admin#6]
个人设置页面切换屏幕时，菜单显示异常。 
参考修复 [ant-desigin-pro](https://github.com/ant-design/ant-design-pro/blob/bf40752ed87fe0bd8073f6a74e39cf485e8fbf32/src/pages/account/settings/index.tsx#L107)

**Comment by xiaodit** [comment]
个人设置页面切换屏幕时，菜单显示异常。 
参考修复 [ant-desigin-pro](https://github.com/ant-design/ant-design-pro/blob/bf40752ed87fe0bd8073f6a74e39cf485e8fbf32/src/pages/account/settings/index.tsx#L107)

**Comment by edenleung** [comment]
fix https://github.com/xiaodit/think-ant-vue/commit/31c1b75eba3f3ec345ae76de332845a8c1cee7a0
